-- Generated by matugen from the current wallpaper. Do not edit by hand.
hl.config({
    general = {
        col = {
            active_border   = "rgba({{colors.outline.default.hex_stripped}}AA)",
            inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}AA)",
        },
    },

    misc = {
        background_color = "rgba({{colors.surface.dark.hex_stripped}}FF)",
    },
})

-- pinned
hl.window_rule({
    name  = "colors-pinned",
    match = { pin = true },
    border_color = "rgba({{colors.primary.default.hex_stripped}}AA) rgba({{colors.primary.default.hex_stripped}}77)",
})

-- fullscreen
hl.window_rule({
    name  = "colors-fullscreen",
    match = { fullscreen = true },
    border_color = "rgba({{colors.primary.default.hex_stripped | auto_lightness: 50.0 }}AA)",
    border_size  = 3,
})
