#!/usr/bin/env bash
# jarvos-sync — the descriptive files written into the user's profile repo:
# the secrets manifest, the "what was left behind" notes, the machine-readable
# summary and the README. Sourced by scripts/jarvos-sync; not run on its own.
#
# These read the capture globals (DENIED_COUNT, SKIPPED_*, MAX_FILE_MB) that the
# caller has already populated.
#
# shellcheck shell=bash

write_secrets_manifest() {
    local stage="$1" out="$1/secrets.manifest" line target
    {
        printf '# JarvOS profile — secrets manifest.\n'
        printf '#\n'
        printf '# Names and locations only. No value from this list is in this repo.\n'
        printf '# Generated by %s %s. Deterministic on purpose: no timestamp, so a\n' "$PROG" "$VERSION"
        printf '# re-capture that found nothing new produces no diff.\n\n'
        printf '## Bring these from your vault\n\n'
        while IFS= read -r line; do
            target="${line%%|*}"; target="${target%"${target##*[![:space:]]}"}"
            if [[ -e "${target/#\~/$HOME}" ]]; then
                printf '%s | PRESENT on the source machine\n' "$line"
            else
                printf '%s | absent on the source machine\n' "$line"
            fi
        done < <(manifest_lines "$JARVOS_ROOT/system/continuity/secrets.manifest.in")

        printf '\n## Environment variables the synced dotfiles expect\n\n'
        grep -rhoIE '\$\{?[A-Z][A-Z0-9_]{2,}\}?' "$stage/dotfiles" 2>/dev/null |
            tr -d '${}' | sort -u |
            grep -E '(TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL|API_KEY|APIKEY|_KEY$|_KEYS$|_PASS$)' |
            sed 's/^/$/' || printf '(none referenced)\n'

        if [[ ${#SKIPPED_SECRET[@]} -gt 0 ]]; then
            printf '\n## Refused by the content gate (they hold secret-shaped strings)\n\n'
            printf '%s\n' "${SKIPPED_SECRET[@]}"
        fi
    } >"$out"
}

write_notes() {
    local stage="$1"
    {
        printf '# What jarvos-sync deliberately left behind\n\n'
        printf 'Denied by system/continuity/dotfiles.deny: %d file(s).\n' "$DENIED_COUNT"
        printf 'Paths are not listed: the denylist covers secrets, history and\n'
        printf 'transcripts, and their names are themselves personal.\n\n'
        printf '## Symlinks (not portable; recreate by hand if you want them)\n\n'
        if [[ ${#SKIPPED_LINK[@]} -gt 0 ]]; then printf '%s\n' "${SKIPPED_LINK[@]}"; else printf '(none)\n'; fi
        printf '\n## Larger than %s MiB (raise JARVOS_SYNC_MAX_FILE_MB to include)\n\n' "$MAX_FILE_MB"
        if [[ ${#SKIPPED_SIZE[@]} -gt 0 ]]; then printf '%s\n' "${SKIPPED_SIZE[@]}"; else printf '(none)\n'; fi
        printf '\n## Host-specific state the new machine regenerates\n\n'
        printf 'monitors.conf, colors.conf, scheme/, .local/state, machine-id.\n'
    } >"$stage/notes.txt"
}

write_profile_json() {
    local stage="$1" pkgs aur units_s units_u dots uvt
    pkgs="$(wc -l <"$stage/packages/explicit.txt")"
    aur="$(wc -l <"$stage/packages/aur.txt")"
    units_s="$(wc -l <"$stage/units/system.txt")"
    units_u="$(wc -l <"$stage/units/user.txt")"
    dots="$(find "$stage/dotfiles" -type f | wc -l)"
    uvt="$(wc -l <"$stage/packages/uv-tools.txt" 2>/dev/null || echo 0)"
    cat >"$stage/jarvos-profile.json" <<EOF
{
  "schema": $PROFILE_SCHEMA,
  "tool": "jarvos-sync",
  "version": "$VERSION",
  "jarvos_release": "$(cat /etc/jarvos-release 2>/dev/null | head -1 || echo unknown)",
  "packages": { "explicit": $pkgs, "aur": $aur },
  "units": { "system": $units_s, "user": $units_u },
  "uv_tools": $uvt,
  "dotfiles": { "files": $dots, "denied": $DENIED_COUNT,
    "skipped_symlink": ${#SKIPPED_LINK[@]}, "skipped_size": ${#SKIPPED_SIZE[@]},
    "skipped_secret": ${#SKIPPED_SECRET[@]} }
}
EOF
}

write_readme() {
    cp "$JARVOS_ROOT/system/continuity/profile-README.md" "$1/README.md"
}

