general {
    col.active_border = rgba(829494AA)
    col.inactive_border = rgba(394a4aAA)
}

misc {
    background_color = rgba(0c1515FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(0c1515FF)
        col.text = rgba(dae4e4FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(dae4e4), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(dae4e4), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(dae4e4), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

# pinned
windowrule = border_color rgba(ffb872AA) rgba(ffb87277), match:pin 1

# fullscreen
windowrule = border_color rgba(723900AA), match:fullscreen 1
windowrule = border_size 3, match:fullscreen 1