-- Generated by matugen from the current wallpaper. Do not edit by hand.
hl.config({
    general = {
        col = {
            active_border   = "rgba(829494AA)",
            inactive_border = "rgba(394a4aAA)",
        },
    },

    misc = {
        background_color = "rgba(0c1515FF)",
    },
})

-- pinned
hl.window_rule({
    name  = "colors-pinned",
    match = { pin = true },
    border_color = "rgba(ffb872AA) rgba(ffb87277)",
})

-- fullscreen
hl.window_rule({
    name  = "colors-fullscreen",
    match = { fullscreen = true },
    border_color = "rgba(723900AA)",
    border_size  = 3,
})
