# Window grouping with gradient tab indicators
group {
    col.border_active = rgba(0DB7D4CC)
    col.border_inactive = rgba(31313600)
    col.border_locked_active = rgba(0DB7D4CC)
    col.border_locked_inactive = rgba(31313600)

    groupbar {
        font_family = JetBrains Mono NF
        font_size = 15
        gradients = true
        gradient_round_only_edges = false
        gradient_rounding = 5
        height = 25
        indicator_height = 0
        gaps_in = 3
        gaps_out = 3

        text_color = rgb(dae4e4)
        col.active = rgba(0DB7D4D4)
        col.inactive = rgba(394a4aD4)
        col.locked_active = rgba(0DB7D4D4)
        col.locked_inactive = rgba(829494D4)
    }
}
