input {
    kb_layout = us
    kb_variant = intl
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    follow_mouse = 2
    focus_on_close = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.5
    }
}

# Per-device keyboard: Lenovo = BR ABNT layout
device {
    name = lenovo-lenovo-traditional-usb-keyboard
    kb_layout = br
    kb_variant =
}

binds {
    scroll_event_delay = 0
    hide_special_on_workspace_change = true
}

cursor {
    zoom_factor = 1
    zoom_rigid = false
    hotspot_padding = 1
}
