accent = "#829494"
cursor = "#d5e4e4"
foreground = "#d5e4e4"
background = "#0c1515"
selection_foreground = "#0c1515"
selection_background = "#a8cccc"
color0 = "#0c1515"
color1 = "#e88d8d"
color2 = "#98bba4"
color3 = "#dbc18e"
color4 = "#9ecccc"
color5 = "#c4acd1"
color6 = "#a8cccc"
color7 = "#d5e4e4"
color8 = "#536767"
color9 = "#ffc0c0"
color10 = "#b8dcc4"
color11 = "#ffe1ae"
color12 = "#bcecec"
color13 = "#e4ccf1"
color14 = "#c8ecec"
color15 = "#f0fafa"
